---
title: "Homework 6"
author: "Emma Sexton"
date: "Due 3 Dec 2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r load_libraries}
library(tidyverse)
library(modelr)
```

## Problem 1

To obtain a distribution for $\hat{r}^2$, we'll follow basically the same procedure we used for regression coefficients: draw bootstrap samples; the a model to each; extract the value I'm concerned with; and summarize. Here, we'll use `modelr::bootstrap` to draw the samples and `broom::glance` to produce `r.squared` values. 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## Problem 2
```{r}
homicide_df <- 
  read_csv(
    'data/homicide-data.csv') %>%  
  janitor::clean_names()
```

```{r}
homicide_summary <- 
  homicide_df %>% 
  mutate(
    city_state = str_c(city, sep = ", ", state),
    victim_age = as.numeric(victim_age),
    hom_solved = ifelse(disposition == "Closed by arrest" | disposition == "Closed without arrest", 1, 0)
  ) %>%
  filter(
    city_state != "Tulsa, AL" | 
    city_state != "Dallas, TX" | 
    city_state != "Phoenix, AZ" | 
    city_state != "Kansas City, MO" & 
    victim_race == "White" | 
    victim_race == "Black"
  )
```

Run logistic regression for Baltimore, MD

```{r}
baltimore_log_df <- homicide_summary %>% 
  filter(city_state == "Baltimore, MD")

baltimore_log_results <- glm(hom_solved ~ victim_age + victim_sex + victim_race, data = baltimore_log_test) %>% 
  broom::tidy()
```




